import project1 from '../assets/project1.png'
import project2 from '../assets/project2.png'

const ProjectListFull=[
    {
        demoLink:"Not Available",
        title:"Project Title Here 1",
        tags:["HTML","CSS","Javascript"],
        description:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work. Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work. Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work. Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        description2:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        img:project1,
        imgFull:[project1,project2,project1]
    },
    {
        demoLink:"Not Available",
        title:"Project Title Here 2",
        tags:["ReactJs","HTML","CSS","Javascript"],
        description:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        img:project2,
        description2:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        imgFull:[project1,project2,project1]
    },
    {
        demoLink:"Not Available",
        title:"Project Title Here 3",
        tags:["ReactJs","HTML","CSS","Javascript"],
        description:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        img:project2,
        description2:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        imgFull:[project1,project2,project1]
    },
    {
        demoLink:"Not Available",
        title:"Project Title Here 4",
        tags:["ReactJs","HTML","CSS","Javascript"],
        description:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        img:project2,
        description2:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        imgFull:[project1,project2,project1]
    },
    {
        demoLink:"Not Available",
        title:"Project Title Here 5",
        tags:["ReactJs","HTML","CSS","Javascript"],
        description:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        img:project2,
        description2:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        imgFull:[project1,project2,project1]
    },
    {
        demoLink:"Not Available",
        title:"Project Title Here 6",
        tags:["ReactJs","HTML","CSS","Javascript"],
        description:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        img:project2,
        description2:"Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.Hello there! My name is Rohit Pratap. I am a front-end web developer & designer, and I'm very passionate and dedicated to my work.",
        imgFull:[project1,project2,project1,project1]
    }
]

export default ProjectListFull